frontend:

  replicaCount: 2

  image:

    repository: mrohan123/frontend

    tag: v1

    pullPolicy: Always

  service:

    type: ClusterIP

    port: 3000

backend:

  replicaCount: 3

  image:

    repository: mrohan123/backend

    tag: v1

    pullPolicy: Always

  service:

    type: ClusterIP

    port: 5000