name: Kubernetes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Show current directory (Debug)
      - name: Debug Repository
        shell: powershell
        run: |
          Write-Host "Current Directory:"
          Get-Location

          Write-Host ""
          Write-Host "Repository Files:"
          Get-ChildItem

          Write-Host ""
          Write-Host "Backend Files:"
          Get-ChildItem .\backend

          Write-Host ""
          Write-Host "Frontend Files:"
          Get-ChildItem .\frontend

      # Docker Login
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Verify Tools
      - name: Verify Tools
        shell: powershell
        run: |
          docker --version
          kubectl version --client
          helm version
          minikube status

      # Build Backend
      - name: Build Backend Image
        shell: powershell
        run: |
          docker build `
            -f .\backend\Dockerfile `
            -t "${{ secrets.DOCKER_USERNAME }}/backend:v${{ github.run_number }}" `
            .\backend

      # Build Frontend
      - name: Build Frontend Image
        shell: powershell
        run: |
          docker build `
            -f .\frontend\Dockerfile `
            -t "${{ secrets.DOCKER_USERNAME }}/frontend:v${{ github.run_number }}" `
            .\frontend

      # Push Backend
      - name: Push Backend Image
        shell: powershell
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/backend:v${{ github.run_number }}"

      # Push Frontend
      - name: Push Frontend Image
        shell: powershell
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/frontend:v${{ github.run_number }}"

      # Check Kubernetes Cluster
      - name: Check Cluster
        shell: powershell
        run: |
          kubectl get nodes

      # Helm Deploy
      - name: Deploy using Helm
        shell: powershell
        run: |
          helm upgrade --install fullstack-app .\helm `
            --set frontend.image.repository=${{ secrets.DOCKER_USERNAME }}/frontend `
            --set frontend.image.tag=v${{ github.run_number }} `
            --set backend.image.repository=${{ secrets.DOCKER_USERNAME }}/backend `
            --set backend.image.tag=v${{ github.run_number }}

      # Verify Deployment
      - name: Verify Deployment
        shell: powershell
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get deployments
          helm list