name: Kubernetes CI/CD

on:
  push:
    branches:
      - main

env:

  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  IMAGE_TAG: v${{ github.run_number }}

jobs:

  deploy:

    runs-on: self-hosted

    steps:

    ####################################

    - name: Checkout Source

      uses: actions/checkout@v4

    ####################################

    - name: Login Docker Hub

      uses: docker/login-action@v3

      with:

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}

    ####################################

    - name: Build Backend

      run: |

        docker build \
        -t $DOCKER_USERNAME/backend:$IMAGE_TAG \
        ./backend

    ####################################

    - name: Build Frontend

      run: |

        docker build \
        -t $DOCKER_USERNAME/frontend:$IMAGE_TAG \
        ./frontend

    ####################################

    - name: Push Backend

      run: |

        docker push $DOCKER_USERNAME/backend:$IMAGE_TAG

    ####################################

    - name: Push Frontend

      run: |

        docker push $DOCKER_USERNAME/frontend:$IMAGE_TAG

    ####################################

    - name: Check Minikube

      run: |

        kubectl get nodes

    ####################################

    - name: Deploy Helm

      run: |

        helm upgrade --install fullstack-app ./helm \
        --set frontend.image.repository=$DOCKER_USERNAME/frontend \
        --set frontend.image.tag=$IMAGE_TAG \
        --set backend.image.repository=$DOCKER_USERNAME/backend \
        --set backend.image.tag=$IMAGE_TAG

    ####################################

    - name: Verify Deployment

      run: |

        kubectl get pods

        kubectl get svc

        kubectl get deployment

        helm list